---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  require_ansible_repo: true
  hosts: test-kitchen
  ansible_verbose: true
  sudo: true
  roles_path: roles

platforms:
- name: ubuntu-trusty64
  driver_plugin: vagrant
  driver_config:
    box: lattice/ubuntu-trusty-64

suites:
 - name: default
