---
# - name: Copy lattice release tarball if exists locally
#   copy: src={{ lattice_tarball }} dest=/usr/local/
#   ignore_errors: yes

- name: Download lattice release tarball
  get_url: url={{ lattice_tarball_url }} dest=/usr/local/{{ lattice_tarball }} force=no

- name: Unpack lattice
  shell: rm -rf /usr/local/lattice-build && tar xfz /usr/local/{{ lattice_tarball }} -C /usr/local/

- stat: path=/etc/init/consul-server.conf
  register: consul_server

- name: Don't run consul-client if consul-server on same machine
  shell: rm -f /etc/init/consul-client.conf
  when: consul_server.stat.isfile is defined and consul_server.stat.isfile

- service: name={{ item }} state=stopped
  ignore_errors: true
  with_items:
  - auctioneer
  - consul-client
  - converger
  - executor
  - garden-linux
  - metron
  - rep

- name: Install and run processes
  shell: /usr/local/lattice-build/diego-cell/install-diego-cell /usr/local/lattice-build/diego-cell
